[tool.poetry]
name = "misc"
version = "0.0.1"
description = "Various personal utilities."
authors = ["Aidan Courtney <aidanfc97@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
typer = "^0.7.0"
rich = "^13.3.2"
pypdf = "^3.5.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
